### ISSUE TITLE
Cannot add a new city

### ISSUE THREAD

**Issue by jaroslawhartman** [jaroslawhartman/TimeZones-Alfred#1]
Due to new policy at google maps, conversion Location -> Time zone does not work.

> Keyless access to Google Maps Platform is deprecated. Please use an API key with all your API calls to avoid service interruption. For further details please refer to http://g.co/dev/maps-no-account

**Comment by jaroslawhartman** [comment]
Fixed in version 2.0

**Comment by hanoii** [comment]
I am not sure on this one, I might give a try to make something functional with something other than google, but I wonder if it wouldn't have made more sense to provide a way to configure an API.

Glad I found the older version as I might fork it from there. Thanks!

**Comment by jaroslawhartman** [comment]
Hi,

I'm not sure if I'm following... Since version 2.0 Google API is not needed anymore. I also made a lot of simplification to remove dependencies to online APIs.

Do you still have problems with this release?

Thank you!

**Comment by hanoii** [comment]
@jaroslawhartman HI! The problem with the current approach (the CSV) is that allows no update. We are now in a timespan where several timezones are changing (London, New York) do to day time savings, how were you planning to account for those?

I still think that some API is needed, either google or something else, and the only thing about google is that you know need an API key that for some is not easy to get. I just wanted to bring back some way to have an updated timezone.

**Comment by jaroslawhartman** [comment]
Hi @hanoii, any more thoughts? Especially regarding my previous comment?

Thank you

**Comment by MrJekkyl** [comment]
Hi, I'm trying to add a new time zone like Paris|France|Europe/Paris|FR|33 
so did I on the edit timezone txt but nothing changes, by the way the "timezone add" is not working and directly going to this : 
<img width="605" alt="capture d ecran 2018-11-09 a 17 57 30" src="https://user-images.githubusercontent.com/44898829/48276717-fdb3d700-e448-11e8-9ce8-29d5e8120099.png">
<img width="605" alt="capture d ecran 2018-11-09 a 17 57 45" src="https://user-images.githubusercontent.com/44898829/48276718-fdb3d700-e448-11e8-8b9d-262f46f46b06.png">

**Comment by jaroslawhartman** [comment]
Hi,

Thank you for this report. Which version you're on? I hoped it will work better in v2.1... If you're not on 2.1, can you try download latest version from e.g. https://jhartman.pl/download/alfred-timezone-workflow/

It's how it works on my version of 2.1. Please note that after typing `timezone add` you should keep typing your city, to eventually get whole sentence `timezone add paris`. I admin, these search options are confusing...

![image](https://user-images.githubusercontent.com/964833/48278177-11f9d300-e44d-11e8-8bb5-fdbece1bf685.png)

Give a try please. If no luck, select `Edit file with defined cities`:

![image](https://user-images.githubusercontent.com/964833/48278304-7026b600-e44d-11e8-961f-796f610b99ff.png)

and add

`Paris|France|Europe/Paris|FR|33`

Eventually my file is:
```
#Version2.0
London|United Kingdom|Europe/London|GB|44
New Delhi|India|Asia/Kolkata|IN|91
New York|United States|America/New_York|US|1
Paris|France|Europe/Paris|FR|33
Warsaw|Poland|Europe/Warsaw|PL|48
```
Which is reflected as:

![image](https://user-images.githubusercontent.com/964833/48278436-c3990400-e44d-11e8-9279-3b3bed3a058a.png)

If still no luck, let's continue our troubleshooting.

Best regards,
Jarek

**Comment by MrJekkyl** [comment]
Problem SOLVED ! Thank you for the Tuto 
And Great work
Cheers

**Comment by jaroslawhartman** [comment]
@MrJekkyl , what was the issue after all?

**Comment by MrJekkyl** [comment]
Sorry, when adding timezone the transition is not immediate so the "google/amazon/wiki search" stays temporarily. By the way it's the V2.0 that appears on the workflow preferences but it's a detail. 
Great tutorial that needed to be done by the way

**Comment by jaroslawhartman** [comment]
> By the way it's the V2.0 that appears on the workflow preferences but it's a detail.

Yeah, noticed that... Raised #8 for that, will be fixed next time.

Best regards,
Jarek

**Comment by jaroslawhartman** [comment]
Closing - since no more feedback and I _believe_ that this has been fixed.
