### ISSUE TITLE
Choose different date

### ISSUE THREAD

**Issue by nevries** [jaroslawhartman/TimeZones-Alfred#15]
Choosing another time is great, but what about choosing a different date also? I suggest to do it by either giving an absolute date or something relative like: in x days.

**Comment by jaroslawhartman** [comment]
Hi @nevries,

This has been actually already implemented, download v2.5:

* **Keyword**: *tz [`date modifier`] [`time`]* - (where `time` is as above and `date modifier` is 'today' (short: 't'), or 'tomorrow' (short: 'tm'), or `[number of days]d` what means to add the number of days to current date, or one of `dd`, `mmdd`, `yymmdd`, `yyyymmdd` to give an absolute date) - convert provided date and time into time of your cities.

I hope this is what was asking about?

Best regards,
Jarek
