### ISSUE TITLE
City name search by parts of the name

### ISSUE THREAD

**Issue by jjarava** [jaroslawhartman/TimeZones-Alfred#17]
Hi!

Currently when doing `tz <some letters>` the list of stored cities is filtered down to the cities that **start with** those letters; it'd be great if the search was over any part of the name

So in this list, 

![image](https://user-images.githubusercontent.com/2682444/57143309-df5ae280-6dbe-11e9-9626-a1a965026180.png)

`tz pau` would give me Sao Paulo, etc...

Thanks!

**Comment by jaroslawhartman** [comment]
Hi, will take a look.

Best regards,
Jarek

**Comment by jaroslawhartman** [comment]
Hi @jjarava 

I trust it has been implemented in v2.5. Take a look please and let me know if this is what you're looking for.

Thank you,
Jarek

**Comment by jjarava** [comment]
Yes, it works well both in 2.5 and 2.6 👍
