### ISSUE TITLE
New release (2.5?)

### ISSUE THREAD

**Issue by jjarava** [jaroslawhartman/TimeZones-Alfred#18]
Hi!

Looking at the code in the repo, it seems that the latest release (v2.5?) is not packaged as a zip for release?

**Comment by jjarava** [comment]
I've seen that the .zip file is available in the repo; just not tagged as a release:

https://github.com/jaroslawhartman/TimeZones-Alfred/blob/master/TimeZones-v2.5.zip

**Comment by jaroslawhartman** [comment]
Indeed, somehow I missed it.

Released.
