### ISSUE TITLE
Not an issue 

### ISSUE THREAD

**Issue by Spark3000** [jaroslawhartman/TimeZones-Alfred#2]
Just wanted to say thanks and couldn't find you on Twitter. Used the old Packal workflow for ages, multiple times a day. This one much faster and better cities. Thanks. 👍

**Comment by jaroslawhartman** [comment]
Hi @Spark3000 , thanks for this feedback! You could contact me through my website [https://jhartman.pl](https://jhartman.pl/tag/time-zones/ ), e.g. leave a comment there.

Best regards,
Jarek
