### ISSUE TITLE
Bundle id change

### ISSUE THREAD

**Issue by xilopaint** [jaroslawhartman/TimeZones-Alfred#20]
Why was bundle id changed on v2.6?

**Comment by jaroslawhartman** [comment]
Hi,

Wanted to upload to [Packal](http://www.packal.org/workflow/timezones-2) to facilitate automatic upgrades etc. But with the old ID it was not possible as I don't own this package.

Best regards,
Jarek

**Comment by xilopaint** [comment]
Packal is unmaintained and broken for auto-updates. Have you ever checked [OneUpdater](https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater)? It's a great solution that support GitHub releases.

**Comment by jaroslawhartman** [comment]
Interesting option, I will take a look.

Thank you, Jarek

**Comment by jaroslawhartman** [comment]
Closing for now.
