### ISSUE TITLE
Add support for utc

### ISSUE THREAD

**Issue by mazinbokhari** [jaroslawhartman/TimeZones-Alfred#22]

**Comment by geoffreywiseman** [comment]
This is the primary thing I wanted `tz` for, and sadly, not currently supported. 😭

**Comment by jaroslawhartman** [comment]
Hi @mazinbokhari !

Could you please describe the usecase? I.e. how the search text should look like?

Thank you,
Jarek

**Comment by geoffreywiseman** [comment]
So, I often deal with servers that are configured for UTC (configuring servers with as the system time zone is a fairly common practice), but not SO often that UTC conversion is natural to me yet. So when I'm looking at a log file, I'll often wonder "What time is that?" and then I'd like to be able to call up Alfred and say "tz utc 14:36" and see what 14:36 UTC is here.  Or I'll want to find something and I know when it happened here, sand I'll want "tz 09:30" to find out what the UTC equivalent that I'd be looking for would be.

**Comment by joshka** [comment]
+1 on this, all my server logs are in UTC, but some sites are in my local TZ and I regularly deal with other countries. Making this work out of the box would would make this amazing.

An easy way to implement this (will do when I have some time) would be to just add the Etc/UTC timezones as special locations in the cities csv file (.e.g UTC = `Etc/UTC`, UTC+1 = `Etc/GMT-1` etc.)

A quick workaround that works in the current version is to add a line in the timezone list file like:
```
UTC|United Kingdom|Etc/UTC|UTC||0|0
UTC+1|United Kingdom|Etc/GMT-1|UTC+1||0|0
```
See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for Timezones that will work in there - note that the value for Etc/GMT-X is reversed. See
https://en.wikipedia.org/wiki/Tz_database#Area for reasons

**Comment by mohoromitch** [comment]
I think the best workaround right now would be to use a city like Reykjavik, which uses GMT (UTC+0) year round. This *does* bring into question daylight savings time support (which is covered in #34) however, but that's beyond the scope of this issue.

**Comment by jaroslawhartman** [comment]
Added to v2.16:

<img width="605" alt="Screenshot 2020-08-16 at 20 06 27" src="https://user-images.githubusercontent.com/964833/90341432-fb0fe980-dfff-11ea-9c06-463d579da64b.png">

<img width="605" alt="Screenshot 2020-08-16 at 20 33 47" src="https://user-images.githubusercontent.com/964833/90341434-ffd49d80-dfff-11ea-92ce-71a3f245a527.png">

Will be released soon.
