### ISSUE TITLE
Netherlands' flag does not display properly

### ISSUE THREAD

**Issue by indigoblueraspberry** [jaroslawhartman/TimeZones-Alfred#24]
The dimensions of the dutch flag are not correct due to the lack of the alpha segments above and below the image to complete a box of 80x80 pixels which is required to display the flag properly. The corrected version of the flag is shown below, I hope it displays the alpha correctly if not let me know.

![netherlands](https://user-images.githubusercontent.com/44578534/59161055-bc1e0400-8add-11e9-9ee1-a711d6b35bf1.png)

**Comment by jaroslawhartman** [comment]
Reproduced as per screenshot below:

![image](https://user-images.githubusercontent.com/964833/59244468-e0c8c780-8c14-11e9-81c3-c51ac4c512b6.png)

**Comment by jaroslawhartman** [comment]
Thank you for reporting, fixed in v10.
