### ISSUE TITLE
how to show timezone: UTC +/- number???

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [jaroslawhartman/TimeZones-Alfred#25]

**Comment by jaroslawhartman** [comment]
Not really possible now.

But it's interesting request. I will mark as enhancement.

**Comment by danielbitzer** [comment]
I tried adding `UTC|N\A|Universal Time|UTC|0|1` to my timezones.txt file.

Works perfectly for me!

![snap](https://d.pr/i/ktI3nM+)

**Comment by jaroslawhartman** [comment]
Hi  guys,

Added to v2.16:

<img width="605" alt="Screenshot 2020-08-16 at 20 06 27" src="https://user-images.githubusercontent.com/964833/90341432-fb0fe980-dfff-11ea-9c06-463d579da64b.png">

<img width="605" alt="Screenshot 2020-08-16 at 20 33 47" src="https://user-images.githubusercontent.com/964833/90341434-ffd49d80-dfff-11ea-92ce-71a3f245a527.png">

Will be released soon.

**Comment by Mr-jiangzhiguo** [comment]
how to show this (UTC-8)
![image](https://user-images.githubusercontent.com/22312092/90642554-1cbdda80-e265-11ea-8408-af555d0108ef.png)

**Comment by jaroslawhartman** [comment]
> how to show this (UTC-8)

I don't think it's possible anymore after migrating to Geo Lite 2.
