### ISSUE TITLE
Add support for AoE Time

### ISSUE THREAD

**Issue by ioemilio** [jaroslawhartman/TimeZones-Alfred#26]
It would be great if one could add the [Anywhere on Earth](https://en.wikipedia.org/wiki/Anywhere_on_Earth) time!

**Comment by chatchavan** [comment]
It seems that we need to add an AOE entry to the `GeoLite2-City-Locations-en.csv`. However, I couldn't figure out what should be the appropriate `geoname_id`.

**Comment by ioemilio** [comment]
According to Wikipedia AoE time is the timezone in Howland and Baker islands. 
It looks like the field `geoname_id` field in the file `GeoLite2-City-Locations-en.csv` is set according to the website [https://www.geonames.org](https://www.geonames.org).

According to the first result of a search on the website it is possible to get that:
* the field `genome_id` for Baker Island is `5854907`
* the field `genome_id` for Howland Island is `5854922`

**Comment by jaroslawhartman** [comment]
Hi guys,

It's been a long time, but.... how does it look?

<img width="619" alt="Screenshot 2020-08-19 at 22 17 08" src="https://user-images.githubusercontent.com/964833/90685293-dfa81700-e269-11ea-8dbc-32448ee85754.png">
<img width="619" alt="Screenshot 2020-08-19 at 22 16 52" src="https://user-images.githubusercontent.com/964833/90685304-e2a30780-e269-11ea-83f0-929d92272481.png">

I hope it's what you requested... At least on my Mac displayed time matches time from [time.is](https://time.is/Anywhere_on_Earth)


Will  be released as v2.17.

**Comment by liyang85** [comment]
Sorry but I found the AoE **DATE** is different between my Mac and [TimeAndDate.com](https://www.timeanddate.com/time/zones/aoe).

<img width="379" alt="Xnip2020-10-30_20-55-02" src="https://user-images.githubusercontent.com/20695423/97708109-3a27e400-1af3-11eb-88ab-5ea2af58ca55.png">

<img width="729" alt="Xnip2020-10-30_20-54-08" src="https://user-images.githubusercontent.com/20695423/97707534-62631300-1af2-11eb-99e2-be71e2657012.png">
