### ISSUE TITLE
don't overwrite existing timezone.txt file on move

### ISSUE THREAD

**Issue by danielb2** [jaroslawhartman/TimeZones-Alfred#27]
Whenever I upgrade and tell the workflow to use my timezone file on dropbox, the old one gets destroyed. I had a backup but silly me ... still managed to screw up.

**Comment by danielb2** [comment]
Actually, I'm not sure it honors the new location after move at all anymore

**Comment by danielb2** [comment]
it also doesn't honor the location where Alfred settings in general are store, but seems to do it's own thing 😮

**Comment by jaroslawhartman** [comment]
Fixed in version v2.14.
