### ISSUE TITLE
Added Amman, Jordan, but it doesn't show the flag

### ISSUE THREAD

**Issue by dansteeves68** [jaroslawhartman/TimeZones-Alfred#30]
I added the city Amman, (Hashemite Kingdom of) Jordan. The flag has a question mark on it. However I can see a Jordan.png file in the source.
<img width="602" alt="Screen Shot 2019-10-10 at 4 50 25 AM" src="https://user-images.githubusercontent.com/1696420/66558699-9d765b00-eb19-11e9-9078-4f924dff49d9.png">

**Comment by dansteeves68** [comment]
The workaround did fix the issue. Thanks.

**Comment by jaroslawhartman** [comment]
Fixed (at least in v2.16), closing
