### ISSUE TITLE
Add a channel to support this project

### ISSUE THREAD

**Issue by chatchavan** [jaroslawhartman/TimeZones-Alfred#33]
I think this is a great work! It would be great to know how can people support the maintenance and enhancement of this project.

**Comment by jaroslawhartman** [comment]
Hi Chat,

Thank you for proposing this.

The project was created as an open source long time ago by a person who I couldn't contact. I only make ad-hoc maintenance hence I don't feel it would be right to monetise not my work :-)

But I will be more than happy to cooperate with other people (developers) and merge valuable improvements to the main branch.

Best  regards,
Jarek
