### ISSUE TITLE
See 12hr and 24hr at the same time?

### ISSUE THREAD

**Issue by jakedeg** [jaroslawhartman/TimeZones-Alfred#36]
I love the workflow. Thank you so much. The only thing I wish it could do that I can't figure out is show 12hr and 24hr results at the same time. So I could change the format to `Both` and see results like `New York 4:52 PM (16:52)`

Is this possible?

**Comment by jaroslawhartman** [comment]
Hi Jake,

Implemented in v2.16:

<img width="605" alt="Screenshot 2020-08-16 at 19 50 35" src="https://user-images.githubusercontent.com/964833/90340661-2263b800-dffa-11ea-90b9-8cd2da67d65d.png">

<img width="605" alt="Screenshot 2020-08-16 at 19 50 14" src="https://user-images.githubusercontent.com/964833/90340665-25f73f00-dffa-11ea-907a-3a8eba94f45b.png">

Will  be released soon.
