### ISSUE TITLE
The AoE date is different between my Mac and TimeAndDate.com

### ISSUE THREAD

**Issue by liyang85** [jaroslawhartman/TimeZones-Alfred#38]
I live in China (`UTC+8`), and all the date and time displayed by the workflow are correct except the AoE **date** which advanced one day.

Below AoE time I read from [TimeAndDate.com](https://www.timeanddate.com/time/zones/aoe):

<img width="379" alt="Xnip2020-10-30_20-55-02" src="https://user-images.githubusercontent.com/20695423/97709432-490f9600-1af5-11eb-95f2-3fa51a576273.png">

<img width="729" alt="Xnip2020-10-30_20-54-08" src="https://user-images.githubusercontent.com/20695423/97709438-4b71f000-1af5-11eb-833a-ba5505f700e2.png">

**Comment by jaroslawhartman** [comment]
Hi @liyang85 

You can fix this manually - open `GeoLite2-City-Locations-en.csv` in your editor and change 

```
99999998,AoE,AoE,N/A,N/A,"Anywhere on Earth (AoE)",N/A,N/A,,,"Anywhere on Earth (AoE)",,UTC-12,0
```

into

```
99999998,AoE,AoE,N/A,N/A,"Anywhere on Earth (AoE)",N/A,N/A,,,"Anywhere on Earth (AoE)",,UTC+12,0
```

Then remove the location and add it again. Released as v2.18.

Best regards,
Jarek

**Comment by liyang85** [comment]
@jaroslawhartman Thanks for your help.

Now the AoE date is right, but the Timezone is wrong, would you like to fix it too?

![image](https://user-images.githubusercontent.com/20695423/97975991-f1c73980-1e04-11eb-9b4b-63d6b48bd21f.png)

![image](https://user-images.githubusercontent.com/20695423/97975955-e2e08700-1e04-11eb-94ad-8cd89d159a4c.png)

**Comment by jaroslawhartman** [comment]
Hi @liyang85 , take a look at v2.19.

Best regards,
Jarek

**Comment by liyang85** [comment]
Thank you very much @jaroslawhartman .
