### ISSUE TITLE
'tz' displays all regions with the same exact time

### ISSUE THREAD

**Issue by computeristic** [jaroslawhartman/TimeZones-Alfred#39]
As usual, I typed tz in Alfred but this time I had nothing in return as if I didn't have the workflow added. I checked the website and realized that I have an old version (2.10). I installed the newest version and when I typed tz I got my list of countries but they all displayed the same exact time (2 hours behind my local time). This is the first time this happened so I'm guessing it could be because we just changed back to standard time from daylight saving time a couple of days ago. I tried removing the workflow, deleting the files in Application Support, deleting cache in Alfred and installing it back again but I got the same output.

**Comment by jaroslawhartman** [comment]
Thank for reporting, this is a regression injected in 2.19. 
Fixed in v2.20.
