### ISSUE TITLE
Showing the same time for cities in different time zones

### ISSUE THREAD

**Issue by filipeestacio** [jaroslawhartman/TimeZones-Alfred#40]
I have added two cities in different time zones (Leeds, in GMT and San Francisco, in PST). Both are showing the same time when queried.

![Screenshot 2020-11-06 at 17 46 23](https://user-images.githubusercontent.com/32681464/98398000-21ba4b00-2058-11eb-9170-6b483856869f.png)

**Comment by jaroslawhartman** [comment]
Hi, please try v2.20 and let me know if this helps.

**Comment by jaroslawhartman** [comment]
Closing as no further feedback from the reporter. Reported issue seemed like a regression, fixed in v2.20
