### ISSUE TITLE
wishlist: release the `.alfredworkflow` directly, not wrapped in another zip

### ISSUE THREAD

**Issue by slippycheeze** [jaroslawhartman/TimeZones-Alfred#41]
G'day.  It'd be nice if the releases were simply the workflow file, not a zip containing it, since that reduces the messing around required to get it installed.  Clearly, not necessary, but it would help keep my personal "installed versions of workflows", uh,  workflow simpler.

Thanks!

**Comment by jschuur** [comment]
I have no idea what to do with these files without a .alfredworkflow and it was non obvious from some quick googling.

Going to have to pass on installing this.

**Comment by jaroslawhartman** [comment]
Hi, @jschuur - this is already in the [Readme](https://github.com/jaroslawhartman/TimeZones-Alfred):
> **Installation steps**
> - Install Alfred
> - Purchase premium version of Alfred to enable Workflows
> - Download latest ZIP file from [releases](https://github.com/jaroslawhartman/TimeZones-Alfred/releases)
> - Unzip and double click to add to Alfred

Do you think that there is anything more to be added there?

Best regards,
Jarek

**Comment by jschuur** [comment]
Apologies, I completely missed that part in the Readme.

**Comment by slippycheeze** [comment]
Hey, @jaroslawhartman, thanks for looking at this.  My request is specifically that the `.alfredworkflow` file is available for download as part of releases, without the extra "extract from the `.zip`" step, if possible.  

The process documentation is fine.  It just makes putting together automatic installation a little more cumbersome than it needs to be.

**Comment by jaroslawhartman** [comment]
Hi @slippycheeze 

Starting from v2.30 I will put `.alfredworkflow` file in the releases (alongside `.zip`).

I will put on my list a procedure for automatised upgrades.

Closing for now.

Best regards,
Jarek
