### ISSUE TITLE
Not working for other countries/places

### ISSUE THREAD

**Issue by krabf** [jaroslawhartman/TimeZones-Alfred#42]
It doesn't work when trying to input other countries/places 
https://ibb.co/LNTCjQn
https://ibb.co/1nXZKcv

**Comment by jaroslawhartman** [comment]
Hi @krabf 

Please follow the guide how to add new countries / cities to the list. It will not work if you try `tz canada`.

> *Keyword*: timezone add [your city] - add your city to the list. (To remove a city, option-select it from the main list.)

![image](https://user-images.githubusercontent.com/964833/100458512-37091f00-30c4-11eb-9a05-b32d26225c54.png)

Best regards,
Jarek

**Comment by jaroslawhartman** [comment]
Closing as no further feedback from the reporter.
