### ISSUE TITLE
add ability to use UTC for "tz <city> <time>" mode

### ISSUE THREAD

**Issue by jeffomatic** [jaroslawhartman/TimeZones-Alfred#43]
Thanks for such a handy tool!

The one thing I've been looking for in an Alfred workflow is a way to take an arbitrary UTC time (usually from a dashboard somewhere) and convert it into my local time. I think this workflow would be perfect for that, because it has a `tz <city> <time>` option, except it seems that "UTC" is not a valid city name.

Would this be difficult to implement? I'm not sure if updating the city CSV file is viable, because it seems like it might be autogenerated or pulled from an official source elsewhere, so the alternative would be to maintain a list of aliases for the cities somewhere...which could be painful.

One thing I tried was renaming the city to "UTC" in my local cities list (just the first column, not the second). If it were possible to use that as a lookup alias, it would solve this problem.

**Comment by cheeth** [comment]
My preference would be `tz <city> <time>` would convert the specified city and time to my timezone. For example, I want to know what time 1pm New York is in my timezone London. currently, I have to specify a day modifier, which I can't understand the point of

**Comment by jaroslawhartman** [comment]
Added a while ago, see https://github.com/jaroslawhartman/TimeZones-Alfred#utc-support

Closing!
