### ISSUE TITLE
Update the "Website" link in the bundle to this GH page

### ISSUE THREAD

**Issue by jjarava** [jaroslawhartman/TimeZones-Alfred#44]
Hi!

When looking at the workflow info in Alfred, the "Website" address is https://jhartman.pl/tag/time-zones/, but unfortunately it seems to be down the couple of times I've tried to look for it (mostly to see about updates etc)

Would it make sense to update the link to the GH page?

Apart from that, **huge kudos** for keeping this workflow alive, I use it _a ton_ 👏!!

**Comment by jaroslawhartman** [comment]
Hi Javier, 

Thanks for reporting, this was an issue with a hosting service I use. Seems to be fixed now, the page is up and running.

Best regards,
Jarek
