### ISSUE TITLE
Copy Output In A Better Formatting

### ISSUE THREAD

**Issue by JaiRelan** [jaroslawhartman/TimeZones-Alfred#45]
Hey @jaroslawhartman,
Firstly, thanks a lot for making this workflow. It's saved me a lot of time and it's pretty helpful.

Just one small modification which I can't figure out myself.

I would like to be able to copy the output and paste it into an email or a message.

For example, when I run command `tz tm 12:00`, the result which gets copied is `Palo Alto, 22:30`. I would prefer to have this date properly formatted so that I can directly send this in an email. An example would be `27 Jan 2021, 22:30 (Palo Alto Time)`.

I also really disliked the pop-up/large text that would come, but I figured out how to disable that.

Cheers and thanks a lot,
J

**Comment by JaiRelan** [comment]
Hey,
Just wanted to follow up and see if you got a chance to check this out...

Cheers and thanks a lot,
J

**Comment by jaroslawhartman** [comment]
Fixed in v2.30:

1. Big banner on copy changed to to MacOS notification #45
2. Changed format of text copied to clipboard (after pressing Enter) - now it's more compact "14:42 (Warsaw)" #45

![image](https://user-images.githubusercontent.com/964833/107372253-81a41000-6ae5-11eb-8a46-48c975644688.png)

Best regards,
Jarek

**Comment by jaroslawhartman** [comment]
More changes in v2.30:
3. Option to change time format copied to clipboard
![image](https://user-images.githubusercontent.com/964833/107374643-1a3b8f80-6ae8-11eb-89fc-8fdf78aae816.png)

**Comment by JaiRelan** [comment]
Hey man,
Thanks a lot for doing this! This workflow is amazingly helpful and thanks for taking the time out to append it with feedback.

Cheers,
J
