### ISSUE TITLE
UTC

### ISSUE THREAD

**Issue by tcurdt** [jaroslawhartman/TimeZones-Alfred#48]
I wanted to also have UTC time listed in my list of timezones - but it isn't exactly a city.
Any suggestions?

**Comment by alfonmga** [comment]
I would love it too. @jaroslawhartman what do you think?

**Comment by alfonmga** [comment]
@tcurdt hey man, [I created a workflow](https://github.com/alfonmga/utc-time-alfred-workflow) for this.

Can you test it out and let me know if it works as expected?  :)
BTW this PR should be closed as this feature request is maybe out-scope for this project.

**Comment by jaroslawhartman** [comment]
Hi guys, I'm not sure if I understand the request. Since a few versions UTC zones can be added to the list; you need to search using keyword `timezone add universal`:

![image](https://user-images.githubusercontent.com/964833/114501067-8aba7600-9c29-11eb-9b49-2e2e255920bd.png)

Best regards,
Jarek

**Comment by tcurdt** [comment]
I didn't see the new releases. Thanks!
