### ISSUE TITLE
Not working! macOs Monterey 12.2

### ISSUE THREAD

**Issue by dandro180** [jaroslawhartman/TimeZones-Alfred#53]
Hi! Thank you for the workflow.

I installed the workflow and it seemed to work fine at first. After some minutes and after adding a couple of cities, I got an error message from the system (not from Alfred) saying that the file will not work anymore because it is not going to be updated for the new versions of macOS. 

Now, it just doesn't work. I, unfortunately, did not take any screenshots of the error message, I just clicked "cancel". In any case when I type the keyword "tz", I just don't get any timezones, I only get the default suggestions to look up the text on google, amazon, etc.

I'm using a 16 inch MacBook Pro 2021 with M1 max with macOs Monterey 12.2

**Comment by inspiredearth** [comment]
I can report it's working on macOS 12.3.1, M1

**Comment by burdo3417** [comment]
its not working in ventura 13.0 neither.
It was working fine before updating.

**Comment by jaroslawhartman** [comment]
What is not working on 13.0? I've just upgraded and on my M1 machine it's OK.

**Comment by jaroslawhartman** [comment]
Hi @dandro180 
>  I got an error message from the system (not from Alfred) saying that the file will not work anymore because it is not going to be updated for the new versions of macOS.

What was the file? 

Can you try to uninstall and reinstall to get more details?

Thank you

**Comment by vitorgalvao** [comment]
> I got an error message from the system (not from Alfred) saying that the file will not work anymore because it is not going to be updated for the new versions of macOS.

@jaroslawhartman It’s bound to be `add_city.sh`, which uses Python 2 in one line. The fix is https://github.com/jaroslawhartman/TimeZones-Alfred/pull/54.
