### ISSUE TITLE
`tz <time>` not displaying results

### ISSUE THREAD

**Issue by dac09** [jaroslawhartman/TimeZones-Alfred#55]
Hi, 

Thanks so much for building this, super useful! 

I found a little bug where entering a query like:

`tz 1400` or `tz 14 Nov 12:00` was not outputting any results (and no errors in the debug console).

### Solution
In order to get it working I had to uncheck the "alfred filter results" option in the tz configuration. 

<img width="1822" alt="Screenshot 2022-11-11 at 12 16 07" src="https://user-images.githubusercontent.com/1521877/201268778-de2d17e1-bf90-437d-b182-a433a93e9bee.png">

---
Details:
- **Workflow Version**: 2.50
- **Alfred Version**: 5.0.5 [2096]
- MacOS 13.0

**Comment by petruut** [comment]
Came here for the same problem - perhaps this could be added to the Wiki?

**Comment by danstreeter** [comment]
I had the same problem - unchecking that made all the additional two/three parameter functions work.

**Comment by yoyoyojoe** [comment]
I'm using Alfred 5. I'm not seeing the same screen for configurations though. Any pointers?

**Comment by BaldrianSector** [comment]
Worked for me as well.  

For clarification, I did the following:

1. Open Alfred Settings
2. Go to TimeZones in Workflows
3. Double click "tz" Script Filter
4. Uncheck: "Alfred filters results"
5. Click "Save"

**Comment by nk9** [comment]
Wow, lifesaver. This looks like an oversight, and it breaks the primary usecase for this Workflow. Has the maintainer abandoned this project?

**Comment by gap777** [comment]
Seems like it.

**Comment by jaroslawhartman** [comment]
Thank you for your participation! Releasing an updated version
